Add weather API aggregator service
ddsm-team/weather-app pull request #5
Opened 2017-06-05 20:07 UTC by szurgot207604

2017-06-06 18:45 UTC, ghost requested changes
Tests?

2017-06-06 18:46 UTC, ghost requested changes
Marked methods that need tests

2017-06-06 18:46 UTC, potasiak207589 commented on src/main/java/pl/lodz/p/ics/weatherapp/api/services/WeatherApiAggregatorService.java
> +    public WeatherApiData getData(Double latitude, Double longitude) {
Test it

2017-06-06 18:46 UTC, potasiak207589 commented on src/main/java/pl/lodz/p/ics/weatherapp/api/services/WeatherApiAggregatorService.java
> +    private WeatherApiData sumData(WeatherApiData data1, WeatherApiData data2) {
Test it

2017-06-06 18:46 UTC, potasiak207589 commented on src/main/java/pl/lodz/p/ics/weatherapp/api/services/WeatherApiAggregatorService.java
> +    private WeatherApiData averageData(WeatherApiData data, Integer divider) {
Test it

2017-06-10 10:51 UTC, szurgot207604 commented on src/main/java/pl/lodz/p/ics/weatherapp/api/services/WeatherApiAggregatorService.java
> +    private WeatherApiData sumData(WeatherApiData data1, WeatherApiData data2) {
won't test private method

2017-06-10 10:52 UTC, szurgot207604 commented on src/main/java/pl/lodz/p/ics/weatherapp/api/services/WeatherApiAggregatorService.java
> +    private WeatherApiData averageData(WeatherApiData data, Integer divider) {
won't test private method

2017-06-10 10:53 UTC, peczek207585 approved these changes

2017-06-10 10:55 UTC, ghost approved these changes

2017-06-10 10:55 UTC, merged